### ISSUE TITLE
Add detection for spotify-launcher install location on Arch

### ISSUE THREAD

**Issue by LegitGreenBoi** [Nuzair46/SpotX-Linux#33]
On Arch you can either install Spotify using the AUR 'spotify' package or the community repository 'spotify-launcher' package. SpotX successfully detects the AUR package Spotify install, but not the spotify-launcher package install. Using the path argument works as a workaround, but it would be nice for the directory to be automatically detected.

spotify-launcher installs Spotify to this directory:
~/.local/share/spotify-launcher/install/usr/share/spotify

EDIT: For anyone still wondering, SpotX's official Bash version supports spotify-launcher and it looks like this repository is no longer needed or supported.
Here's the official version, use this instead: https://github.com/SpotX-Official/SpotX-Bash

**Comment by akumaaayush** [comment]
+1
It used to be detected after the ```Spotify not found in PATH. Searching for Spotify directory..``` 
Now it doesn't.

**Comment by vsdhaliwal** [comment]
have you tried using curl 
`curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg`

`echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list`

then install the client
`sudo apt-get update && sudo apt-get install spotify-client`

**Comment by rxfrxctxd** [comment]
@vsdhaliwal They are on Arch, not a Debian based distribution.

**Comment by vsdhaliwal** [comment]
@akumaaayush you on arch too ? Have you added it to the path

**Comment by akumaaayush** [comment]
@vsdhaliwal, Yes I'm on arch too. The spotify-launcher is already on the path upon install.

**Comment by Mylloon** [comment]
Until SpotX finds it, you can specify where Spotify is located: `$HOME/.local/share/spotify-launcher/install/usr/share/spotify`

Following the README example, you can do : `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -ceP $HOME/.local/share/spotify-launcher/install/usr/share/spotify`

**Comment by SmurgBurglar** [comment]
The command fir my steam deck was : `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -ceP /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/7a095d1e1ffc3a1aa42a58579a9a733950c8eac306b1b2cd38495c2811bb4744/files/extra/share/spotify`

**Comment by LegitGreenBoi** [comment]
> The command fir my steam deck was : `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -ceP /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/7a095d1e1ffc3a1aa42a58579a9a733950c8eac306b1b2cd38495c2811bb4744/files/extra/share/spotify`

You're using the Flatpak version of Spotify, not spotify-launcher.

**Comment by devolskii** [comment]
> You're using the Flatpak version of Spotify, not spotify-launcher.

Will SpotX work with the flatpak version? I cannot find the path for this. I am using arch.

**Comment by kir68k** [comment]
> Will SpotX work with the flatpak version? I cannot find the path for this. I am using arch.

@devolskii Does [this](https://github.com/SpotX-CLI/SpotX-Linux#flatpak-version/) part of the README not work for you? I don't use Spotify or Arch, but that should work.
If you installed Spotify for your user instead of system, replace `/var/lib/flatpak/app` with `/home/$USER/.var/app/` instead from that command.

**Comment by misbahulsaad** [comment]
> Until SpotX finds it, you can specify where Spotify is located: `$HOME/.local/share/spotify-launcher/install/usr/share/spotify`
> 
> Following the README example, you can do : `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -ceP $HOME/.local/share/spotify-launcher/install/usr/share/spotify`

this one works. Thanks man.

**Comment by mrkylegp** [comment]
+1 for this issue.

The solution posted by @Mylloon worked for me. I used spotify from the AUR (yay -S spotify) and then bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -ceP $HOME/.local/share/spotify-launcher/install/usr/share/spotify

**Comment by LegitGreenBoi** [comment]
**This repo is inactive.**

Everyone should use the new version instead where the spotify-launcher issue is fixed:

https://github.com/SpotX-Official/SpotX-Bash
